application: phpfyildirim
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true

# Serve php scripts.
- url: /(.+\.php)$
  script: \1

- url: /
  script: main.php
  
- url: /helloworld
  script: /helloworld.php

- url: /busreis
  script: /busreis.php

- url: /kerstboom
  script: /kerstboom.php

- url: /whilefor
  script: /whilefor.php

- url: /zwemclub
  script: /zwemclub.php
  
- url: /kapper
  script: /kapper.php